services:
  - type: web
    name: negentropy-ml-service
    env: docker
    region: frankfurt
    plan: free
    rootDir: ml-service
    buildCommand: docker build -t negentropy-ml-service .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
